// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbplphhwmymphxuhznwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicGxwaGh3bXltcGh4dWh6bndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDY1MDEsImV4cCI6MjA3MDkyMjUwMX0.9ZIP3eELF0cvNRUW4wg_9amGPAK1A-YuGcZ2O2WQqxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});